handlebars:
  prettyPrint: true
  exposeRequestAttributes: false
  exposeSessionAttributes: true
  allowRequestOverride: true
  exposeSpringMacroHelpers: true
  resolver:
    method: true
    field: true